version: '3.8'
services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - shortener
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    networks:
      - shortener

networks:
  shortener:
    driver: bridge
