spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:h2:mem:app-db
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  liquibase:
    change-log: classpath:changelog/db.changelog-master.yaml
