spring:
  application:
    name: url-shortener
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:app-db
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
